repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.(ai|gz)$
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    - id: parsable-R
    - id: no-browser-statement
    - id: readme-rmd-rendered
    - id: deps-in-desc
      exclude: data\-raw
    - id: use-tidy-description
    - id: style-files
    - id: lintr
      args: [--warn_only]
      verbose: true
    - id: roxygenize
