image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_BASENAME: registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  DOCKER_DRIVER: overlay2

stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build-cellphonedb-queries:
  stage: build
  script:
    - docker pull $IMAGE_BASENAME || true
    - docker build --cache-from $IMAGE_BASENAME --pull -t $IMAGE_BASENAME .
    - docker push $IMAGE_BASENAME
