language: r
sudo: false
cache: packages
r_packages:
    - rjson
    - XML
    - jsonlite
    - rmarkdown
    - covr
    - withr
#r_github_packages:
#    - jimhester/robustr
#    - jimhester/covr
after_success:
        - Rscript -e 'library(covr);coveralls()'
notifications:
  slack:
    secure: gsOT9d72jXfBuJgno2xhHKpJoWy6HT0zqF10NIvWz/aZpxmClFCdKO07zAieI+qOS57d5LNN2P2C8kQrk6SleqwzX0dhBiWtYaaC88AN61/ykszftMIbuJ3c0gJvLP9CqnuN1hrORx7awOTVe/OOKs2uHVzkyVMG+ifn57jShD8=
