
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-10-14T14:47:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "24de937fb9f9104d3cf3a4fa64c83109a47122db",
 "version": "2025.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
