name: Download and Push R Packages

on:
  workflow_dispatch:
  schedule:
    # 定时运行（可选），此处设置为每天运行
    - cron: "0 0 * * *"

permissions:
  contents: write  # 授予工作流对代码库内容的写权限

jobs:
  download-and-push:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 设置 R 环境
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.2" # 确保使用合适的 R 版本

    # 安装系统依赖
    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          libmagick++-dev libgeos-dev libgfortran5 liblapack-dev libblas-dev \
          libpng-dev libjpeg-dev librsvg2-dev libcairo2-dev libnode-dev libproj-dev \
          libxml2-dev libcurl4-openssl-dev libssl-dev libhdf5-dev libv8-dev \
          libfontconfig1-dev libharfbuzz-dev libfribidi-dev libgdal-dev \
          libfreetype6-dev libtiff5-dev libudunits2-dev

    # 安装R脚本所需的包
    - name: Install R packages
      run: |
        Rscript -e "install.packages(c('devtools', 'remotes', 'packrat', 'miniCRAN'), repos='https://cloud.r-project.org/')"

    # 运行R脚本
    - name: Run the R script
      run: |
        Rscript .github/scripts/download_from_github.R

    # 配置git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # 提交下载的文件
    - name: Push downloaded packages
      run: |
        git add r_packages_with_deps
        git commit -m "Add downloaded R packages"
        git push
