name: Emergency Cleanup Large Files
 
on:
  workflow_dispatch:
 
jobs:
  cleanup_large_files:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
 
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
 
      - name: Find and Remove Large Files from Git
        run: |
          echo "=== Finding large files in repository ==="
          
          # 查找所有大于100MB的文件
          find . -type f -size +100M -exec ls -lh {} \; | while read line; do
            echo "Large file found: $line"
          done
          
          echo ""
          echo "=== Removing large files from Git history and current state ==="
          
          # 移除特定的大文件
          large_files=(
            "CRAN_Bioc_backup/TxDb.Hsapiens.UCSC.hg38.knownGene/TxDb.Hsapiens.UCSC.hg38.knownGene/inst/extdata/TxDb.Hsapiens.UCSC.hg38.knownGene.sqlite"
          )
          
          for file in "${large_files[@]}"; do
            if [ -f "$file" ]; then
              echo "Removing large file: $file"
              # 从Git历史中完全移除
              git filter-branch --force --index-filter "git rm -rf --cached --ignore-unmatch '$file'" --prune-empty --tag-name-filter cat -- --all
              # 删除本地文件
              rm -f "$file"
            fi
          done
          
          # 查找并移除其他可能的大文件
          find . -type f -size +100M | while read file; do
            echo "Removing large file: $file"
            git rm -f "$file" 2>/dev/null || true
            rm -f "$file"
          done
          
          # 清理Git历史
          git reset --hard HEAD~1 2>/dev/null || true
          git clean -fd
          
          echo ""
          echo "=== Current Git status ==="
          git status
 
      - name: Force Push Clean Repository
        run: |
          echo "Force pushing cleaned repository..."
          git push origin main --force
