name: Unzip and Commit

on:
  workflow_dispatch: # 允许手动运行 Workflow

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Find and Unzip all .zip Files in Repo
        run: |
          find . -type f -name "*.zip" | while read zip_file; do
            unzip -o "$zip_file" -d "$(dirname "$zip_file")"
          done
          
      - name: Pull latest changes
        run: |
          git pull origin main --rebase
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped .zip files and added extracted content"
          git push
